//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNavigation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int TraceId { get; set; }
        public string DeparturePlace { get; set; }
        public string DestinationPlace { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
